trigger:
  paths:
    include:
    - ConnectionReferences/solution/*

pool:
  vmImage: windows-latest

variables:
- template: ../yaml/templates/build-solution-variables.yml
  parameters:
    SolutionUniqueName: ContosoConnectionReferences

steps:
- template: ../yaml/templates/build-solution.yml
  parameters:
    SolutionFolderPath: ConnectionReferences/solution
    SolutionUniqueName: ContosoConnectionReferences
