trigger:
  paths:
    include:
    - ConnectionReferences/solution/*

pool:
  vmImage: windows-latest

steps:
- template: yaml/templates/build-solution.yml
  parameters:
    SolutionFolderPath: ConnectionReferences/solution
    SolutionUniqueName: ContosoConnectionReferences
