trigger:
  paths:
    include:
    - Flows/solution/*

pool:
  vmImage: windows-latest

variables:
- template: ../yaml/templates/build-solution-variables.yml
  parameters:
    SolutionUniqueName: ContosoFlows

steps:
- template: ../yaml/templates/build-solution.yml
  parameters:
    SolutionFolderPath: Flows/solution
    SolutionUniqueName: ContosoFlows
