trigger: none

resources:
  pipelines:
  - pipeline: BuildCanvasApps
    branch: main
    source: BuildCanvasApps
    trigger:
      branches:
      - main
  - pipeline: BuildConnectionReferences
    branch: main
    source: BuildConnectionReferences
    trigger:
      branches:
      - main
  - pipeline: BuildDataModel
    branch: main
    source: BuildDataModel
    trigger:
      branches:
      - main
  - pipeline: BuildFlows
    branch: main
    source: BuildFlows
    trigger:
      branches:
      - main
  - pipeline: BuildPlugins
    branch: main
    source: BuildPlugins
    trigger:
      branches:
      - main

jobs:
- deployment:
  environment: production
  strategy:
    runOnce:
      deploy:
        pool:
          vmImage: windows-latest
        steps:
        - checkout: self