trigger: none

resources:
  pipelines:
  - pipeline: BuildCanvasApps
    branch: main
    source: BuildCanvasApps
    trigger:
      branches:
      - main
  - pipeline: BuildConnectionReferences
    branch: main
    source: BuildConnectionReferences
    trigger:
      branches:
      - main
  - pipeline: BuildDataModel
    branch: main
    source: BuildDataModel
    trigger:
      branches:
      - main
  - pipeline: BuildFlows
    branch: main
    source: BuildFlows
    trigger:
      branches:
      - main
  - pipeline: BuildPlugins
    branch: main
    source: BuildPlugins
    trigger:
      branches:
      - main

jobs:
- deployment:
  environment: production
  variables:
  - group: Production
  - group: ClientCredentials
  strategy:
    runOnce:
      deploy:
        pool:
          vmImage: windows-latest
        steps:
        - checkout: self
        - task: PowerShell@2
          inputs:
            filePath: powershell/environment-setup/Initialize-Context.ps1
            arguments: |
              -Url $env:URL `
              -ClientId $env:CLIENT_ID `
              -ClientSecret $env:CLIENT_SECRET
          env:
            URL: $(Url)
            CLIENT_ID: $(ClientId)
            CLIENT_SECRET: $(ClientSecret)
          name: EstablishConnection
        - task: PowerShell@2
          inputs:
            filePath: powershell/solutions/Import-Solution.ps1
            arguments: |
              -SolutionZipFilePath $env:SOLUTION_ZIP_FILE_PATH `
              -Managed
          env:
            SOLUTION_ZIP_FILE_PATH: $(Pipeline.Workspace)/BuildCanvasApps/ContosoCanvasApps_managed.zip
            VERSION_NUMBER: $(versionNumber)
          name: ImportCanvasApps