trigger: none

resources:
  pipelines:
  - pipeline: BuildCanvasApps
    branch: main
    source: BuildCanvasApps
    trigger:
      branches:
      - main
  - pipeline: BuildConnectionReferences
    branch: main
    source: BuildConnectionReferences
    trigger:
      branches:
      - main
  - pipeline: BuildDataModel
    branch: main
    source: BuildDataModel
    trigger:
      branches:
      - main
  - pipeline: BuildFlows
    branch: main
    source: BuildFlows
    trigger:
      branches:
      - main
  - pipeline: BuildPlugins
    branch: main
    source: BuildPlugins
    trigger:
      branches:
      - main

jobs:
- deployment:
  environment: production
  pool:
    vmImage: windows-latest
  variables:
  - group: Production
  - group: ClientCredentials
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerPlatformImportSolution@0
          inputs:
            authenticationType: 'PowerPlatformEnvironment'
            PowerPlatformEnvironment: 'production'
            SolutionInputFile: '$(Pipeline.Workspace)/BuildDataModel/packed-solution/ContosoDataModel_managed.zip'
            AsyncOperation: true
        - task: PowerPlatformImportSolution@0
          inputs:
            authenticationType: 'PowerPlatformEnvironment'
            PowerPlatformEnvironment: 'production'
            SolutionInputFile: '$(Pipeline.Workspace)/BuildConnectionReferences/packed-solution/ContosoConnectionReferences_managed.zip'
            AsyncOperation: true
        - task: PowerPlatformImportSolution@0
          inputs:
            authenticationType: 'PowerPlatformEnvironment'
            PowerPlatformEnvironment: 'production'
            SolutionInputFile: '$(Pipeline.Workspace)/BuildFlows/packed-solution/ContosoFlows_managed.zip'
            AsyncOperation: true
        - task: PowerPlatformImportSolution@0
          inputs:
            authenticationType: 'PowerPlatformEnvironment'
            PowerPlatformEnvironment: 'production'
            SolutionInputFile: '$(Pipeline.Workspace)/BuildCanvasApps/packed-solution/ContosoCanvasApps_managed.zip'
            AsyncOperation: true
        - task: PowerPlatformImportSolution@0
          inputs:
            authenticationType: 'PowerPlatformEnvironment'
            PowerPlatformEnvironment: 'production'
            SolutionInputFile: '$(Pipeline.Workspace)/BuildPlugins/packed-solution/ContosoPlugins_managed.zip'
            AsyncOperation: true
